name: db-dev
services:
  postgres:
    image: postgres:18
    ports:
      - 5432:5432
    volumes:
      - bunnfn-data:/var/lib/postgresql/18/data
    environment:
      - POSTGRES_PASSWORD=ruffee
      - POSTGRES_USER=corey
      - POSTGRES_DB=db_dev
volumes:
  bunnfn-data:
