-- This migration tears down the tables for the full data model.

DROP TABLE IF EXISTS roast_event_input_bean CASCADE;
DROP TABLE IF EXISTS recipe_step_ingredient CASCADE;
DROP TABLE IF EXISTS recipe_ingredient CASCADE;
DROP TABLE IF EXISTS blend_coffee CASCADE;

DROP TABLE IF EXISTS taste CASCADE;
DROP TABLE IF EXISTS purchase CASCADE;
DROP TABLE IF EXISTS recipe_step CASCADE;
DROP TABLE IF EXISTS recipe CASCADE;
DROP TABLE IF EXISTS blend CASCADE;
DROP TABLE IF EXISTS coffee_bean CASCADE;
DROP TABLE IF EXISTS roast_stage CASCADE;
DROP TABLE IF EXISTS roast_event CASCADE;
DROP TABLE IF EXISTS roast_profile CASCADE;
DROP TABLE IF EXISTS roast_recipe_step CASCADE;
DROP TABLE IF EXISTS roast_recipe CASCADE;
DROP TABLE IF EXISTS mill_event CASCADE;
DROP TABLE IF EXISTS grow_event CASCADE;

DROP TABLE IF EXISTS seller CASCADE;
DROP TABLE IF EXISTS farmer CASCADE;
DROP TABLE IF EXISTS farm CASCADE;
DROP TABLE IF EXISTS miller CASCADE;
DROP TABLE IF EXISTS mill CASCADE;
DROP TABLE IF EXISTS roaster CASCADE;
DROP TABLE IF EXISTS roastery CASCADE;

DROP TABLE IF EXISTS ingredient CASCADE;
DROP TABLE IF EXISTS roast_machine CASCADE;
DROP TABLE IF EXISTS processing_method CASCADE;
DROP TABLE IF EXISTS variety CASCADE;
DROP TABLE IF EXISTS region CASCADE;
DROP TABLE IF EXISTS origin CASCADE;